### ISSUE TITLE
Missing JSPM config.js?

### ISSUE THREAD

**Issue by m99coder** [davinkevin/Angular2-Sandbox#1]
Hi Kevin,

did you missed to commit the JSPM `config.js`? Your `postinstall` hook of npm starts `jspm install`. It detects the missing `config.js` and starts asking its questions. Answering all of them with „Yes“ configures JSPM to use Babel as transpiler. But I think this isn’t as intended because you added `"typescript": "npm:typescript@^1.8.2"` to jspm `devDependencies` in the `package.json` file.

With kind regards
Marco

**Comment by davinkevin** [comment]
Yeah, because of a wildcard on *.js in the .gitignore, I do the correction

**Comment by davinkevin** [comment]
Fixed in https://github.com/davinkevin/Angular2-Sandbox/commit/729dcaa8b502465898ee7a14247092308a9a6e38

Could you confirm ? If Ok, you can close the ticket.

**Comment by m99coder** [comment]
Perfect. Thank you for the quick fix.
